name: 'Build and Deploy'
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - {name: Checkout Repo, uses: actions/checkout@master}
      - {name: Install Node, uses: actions/setup-node@master, with: {node-version: 14.x}}
      - {name: Install Dependencies, run: 'npm install'}
      - {name: Build, run: 'npm run build'}
      - {name: Install Firebase, run: 'npm install -g firebase-tools'}
      - {name: Deploy To Firebase, run: 'firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"'}
      
